In [ ]:
# Assignment:
# Create 4x4 array of all True values

In [1]:
import numpy as np

In [5]:
np.ones((4, 4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
np.full((4,4), True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
#Create 4x4 array of all False values
np.zeros((4, 4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [7]:
# Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [8]:
# Create 4x4 array of Digonal elements as True and Non diagonal elements as False
np.eye(4, dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [10]:
# Create 4x4 array of Digonal elements as False and Non diagonal elements as True
~np.eye(4, dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [23]:
a=np.eye(4,dtype=bool)

np.logical_not(a)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])